PREFIX stg:  <https://aa.perseus.org/staging#>
PREFIX crm:  <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aat:  <http://vocab.getty.edu/aat/>

CONSTRUCT {
  ?obj a crm:E22_Human-Made_Object ;
       crm:P67i_is_referred_to_by ?noteDesc ;
       crm:P67i_is_referred_to_by ?noteComm ;
       crm:P67i_is_referred_to_by ?noteLabel ;
       crm:P67i_is_referred_to_by ?noteDecorationDesc . # Added decoration description

  ?noteDesc a crm:E33_Linguistic_Object ;
            rdfs:label "Description"@en ;
            crm:P190_has_symbolic_content ?desc ;
            crm:P2_has_type aat:300435416 . # descriptions (narrative texts)

  ?noteComm a crm:E33_Linguistic_Object ;
            rdfs:label "Commentary"@en ;
            crm:P190_has_symbolic_content ?comm ;
            crm:P2_has_type aat:300056130 . # commentaries

  ?noteLabel a crm:E33_Linguistic_Object ;
             rdfs:label "Label text"@en ;
             crm:P190_has_symbolic_content ?label ;
             crm:P2_has_type aat:300411884 . # labels (identifying marks)

  ?noteDecorationDesc a crm:E33_Linguistic_Object ; # New for decoration description
                      rdfs:label "Decoration Description"@en ;
                      crm:P190_has_symbolic_content ?decorationDesc ;
                      crm:P2_has_type aat:300435416 . # descriptions (narrative texts)
}
WHERE {
  ?s a stg:Object ; stg:source ?src ; stg:objectid ?oid .
  BIND( IRI(CONCAT("https://aa.perseus.org/id/thing/", SHA256(CONCAT(?src, ":", STR(?oid))))) AS ?obj )

  OPTIONAL {
    ?s stg:description ?desc .
    BIND( IRI(CONCAT("https://aa.perseus.org/id/text/", SHA256(CONCAT("desc|", STR(?obj))))) AS ?noteDesc )
  }

  OPTIONAL {
    ?s stg:commentary ?comm .
    BIND( IRI(CONCAT("https://aa.perseus.org/id/text/", SHA256(CONCAT("comm|", STR(?obj))))) AS ?noteComm )
  }

  OPTIONAL {
    ?s stg:labeltext ?label .
    BIND( IRI(CONCAT("https://aa.perseus.org/id/text/", SHA256(CONCAT("label|", STR(?obj))))) AS ?noteLabel )
  }
  
  OPTIONAL { # New section for decoration description
    ?s stg:decoration_description ?decorationDesc .
    BIND( IRI(CONCAT("https://aa.perseus.org/id/text/", SHA256(CONCAT("decorationDesc|", STR(?obj))))) AS ?noteDecorationDesc )
  }
}
